# Breast Cancer - Training  Models in Azure ML

In [2]:
import argparse
import os
import sklearn
import pandas as pd 
import numpy as np
from sklearn.metrics import f1_score,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from azureml.core import Run, Dataset
from sklearn.preprocessing import LabelEncoder

In [4]:
from azureml.core import  Workspace,Environment
from azureml.core.authentication import InteractiveLoginAuthentication
interactive_auth = InteractiveLoginAuthentication(tenant_id="9ce70869-60db-44fd-abe8-d2767077fc8f")

ws = Workspace.from_config()


In [17]:
print('Workspace name: ' + ws.name, 
      'Azure region: ' + ws.location, 
      'Subscription id: ' + ws.subscription_id, 
      'Resource group: ' + ws.resource_group, sep = '\n')

Workspace name: cselscdhazureml
Azure region: eastus2
Subscription id: 320d8d57-c87c-4434-827f-59ee7d86687a
Resource group: CSELS-CDH-DEV


In [8]:
ws = Workspace.from_config()
environments = Environment.list(workspace=ws)
for env in environments:
    if env =='breast_cancer_training_env':
        print(env)

In [18]:
# https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data
df = pd.read_csv('./data/cancer_data.csv',header=0,sep=',')
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [19]:
len(df.columns)


32

In [20]:
y = df['diagnosis'].astype('category')
X = df.drop('diagnosis',axis=1)

lbl_encoder = LabelEncoder()
y_encode = lbl_encoder.fit_transform(y)

print("cols:",X.columns)
print("X shape", X.shape)
print("encoder:", lbl_encoder.classes_)
print("y encode:", y_encode.shape)

cols: Index(['id', 'radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')
X shape (569, 31)
encoder: ['B' 'M']
y encode: (569,)


In [21]:
x_train,x_test,y_train,y_test = train_test_split(X,y_encode,train_size=0.75,random_state=42,stratify =y_encode)

print(x_train.shape)
print(y_train.shape)

print(x_test.shape)
print(y_test.shape)

(426, 31)
(426,)
(143, 31)
(143,)


In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [23]:
clf = LogisticRegression()
clf.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
accuracy_score(y_train,clf.predict(x_train))

0.9882629107981221

In [12]:
accuracy_score(y_test,clf.predict(x_test))

0.965034965034965

In [13]:
x_train

array([[ 0.39384567, -0.7457497 , -0.22189399, ..., -0.75526511,
        -0.2651798 , -1.06401285],
       [-0.24763061,  1.80931999, -0.47891277, ...,  1.45360387,
        -0.34586005, -0.74583427],
       [-0.18972429, -0.65070334, -0.1074038 , ..., -0.6993463 ,
        -0.58948278, -0.22039148],
       ...,
       [-0.18751276, -0.32642754,  1.33891103, ..., -0.84967547,
        -0.95175295, -1.17380687],
       [-0.24755471,  0.00903019,  0.26410518, ...,  0.28218803,
        -0.59106475, -0.29601491],
       [-0.2477312 ,  1.71706912,  1.78986218, ...,  0.82470663,
         0.38500814, -0.21703043]])

In [14]:
rf = RandomForestClassifier(n_estimators=40,max_depth=100,max_features=None,min_samples_leaf=3)
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=100, max_features=None,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [14]:
print(f"Training accuracy :{accuracy_score(y_train,rf.predict(x_train)) } , Test accucacy: {accuracy_score(y_test,rf.predict(x_test))}")

Training accuracy :0.9929577464788732 , Test accucacy: 0.9790209790209791


In [15]:
record = x_train[0].tolist()
print(record)
instance = pd.DataFrame(record).transpose()
rf.predict(instance)

[0.393845668409139, -0.7457496952627328, -0.22189398515428446, -0.7676382304726264, -0.6999246324662508, -0.17745016145311038, -0.81484548808207, -0.770581761525873, -0.7189314051409194, 0.07367558407930598, -0.4665409990624931, -0.06425072325003647, -0.667435753669589, -0.10209930505592255, -0.2928749021935234, -0.18393920631817678, -0.8204798568998558, -0.6065568523529427, -0.395651155530143, 0.3134950272756633, -0.8678658791041564, -0.6897420117050609, -0.5598110994362666, -0.723009965205552, -0.6542518616646612, -0.5936861839456196, -0.9574791012332506, -0.9270503937797329, -0.7552651134179409, -0.2651797994882257, -1.0640128515011344]


array([0])

In [16]:
sklearn.__version__

'0.22.1'

In [17]:
import pandas as pd 

input_sample = np.array([[0.393845668409139, -0.7457496952627328, -0.22189398515428446, -0.7676382304726264, -0.6999246324662508, -0.17745016145311038, 
-0.81484548808207, -0.770581761525873, -0.7189314051409194, 0.07367558407930598, -0.4665409990624931, -0.06425072325003647, -0.667435753669589, 
-0.10209930505592255, -0.2928749021935234, -0.18393920631817678, -0.8204798568998558, -0.6065568523529427, -0.395651155530143, 0.3134950272756633,
 -0.8678658791041564, -0.6897420117050609, -0.5598110994362666, -0.723009965205552, -0.6542518616646612, -0.5936861839456196,
 -0.9574791012332506, -0.9270503937797329, -0.7552651134179409, -0.2651797994882257, -1.0640128515011344]])

input = pd.DataFrame(data=input_sample)
rf.predict(input)

array([0])

## Run Training on AzureML

In [19]:
from azureml.core import Workspace, Experiment, Run
from azureml.core.compute import ComputeTarget, AmlCompute
from azureml.core.compute_target import ComputeTargetException
from azureml.core import ScriptRunConfig, Environment
from azureml.widgets import RunDetails

In [20]:
exp = Experiment(workspace=ws, name="RF-BreastCancer")

In [22]:
sklearn_env = Environment.from_conda_specification(name='sklearn-env', file_path='conda_dependencies.yml')
# Specify a GPU base image
sklearn_env.docker.enabled = True

'enabled' is deprecated. Please use the azureml.core.runconfig.DockerConfiguration object with the 'use_docker' param instead.


### Create Compute Target

In [34]:
clustername = 'StandardDS12CPU'
is_new_cluster = False
try:
    gpu_cluster = ComputeTarget(workspace = ws,name= clustername)
    print("Find the existing cluster")
except ComputeTargetException:
    print("Cluster not find - Creating cluster.....")
    is_new_cluster = True
    compute_config = AmlCompute.provisioning_configuration(vm_size='STANDARD_D2_V2',
                                                            vnet_name='csels-cdh-dev-vnet',
                                                            vnet_resourcegroup_name='CSELS-CDH-DEV',
                                                            subnet_name='cdh-azml-dev-snet',
                                                           max_nodes=4)
    gpu_cluster = ComputeTarget.create(ws, clustername, compute_config)

gpu_cluster.wait_for_completion(show_output=True)

Cluster not find - Creating cluster
SucceededProvisioning operation finished, operation "Succeeded"
Succeeded
AmlCompute wait for completion finished

Minimum number of nodes requested have been provisioned


### Load data in data store 

In [35]:
data_store = ws.get_default_datastore()
data_store.upload(src_dir='./data',target_path='cancer_data',overwrite=True,show_progress=True)

Uploading an estimated of 9 files
Uploading ./data/.amlignore.amltmp
Uploaded ./data/.amlignore.amltmp, 1 files out of an estimated total of 9
Uploading ./data/test/.amlignore
Uploaded ./data/test/.amlignore, 2 files out of an estimated total of 9
Uploading ./data/test/.amlignore.amltmp
Uploaded ./data/test/.amlignore.amltmp, 3 files out of an estimated total of 9
Uploading ./data/train/.amlignore
Uploaded ./data/train/.amlignore, 4 files out of an estimated total of 9
Uploading ./data/train/.amlignore.amltmp
Uploaded ./data/train/.amlignore.amltmp, 5 files out of an estimated total of 9
Uploading ./data/.amlignore
Uploaded ./data/.amlignore, 6 files out of an estimated total of 9
Uploading ./data/cancer_data.csv
Uploaded ./data/cancer_data.csv, 7 files out of an estimated total of 9
Uploading ./data/test/test.csv
Uploaded ./data/test/test.csv, 8 files out of an estimated total of 9
Uploading ./data/train/train.csv
Uploaded ./data/train/train.csv, 9 files out of an estimated total of 9

$AZUREML_DATAREFERENCE_357de05320d74186b23878de119058ae

### Training scritps

In [37]:
estimator = ScriptRunConfig(source_directory='./scripts',
                      script='train.py',
                      compute_target=gpu_cluster,
                      environment=sklearn_env)

In [38]:
# TODO: Submit your experiment
run = exp.submit(estimator)

In [39]:
from azureml.widgets import RunDetails
RunDetails(run).show()

_UserRunWidget(widget_settings={'childWidgetDisplay': 'popup', 'send_telemetry': False, 'log_level': 'INFO', '…

In [31]:
from azureml.core.model import Model as AMLModel

In [32]:
AMLModel.register(workspace=ws,model_name='breast-cancer', model_path="./outputs/cancer_model.pkl")

Registering model breast-cancer


Model(workspace=Workspace.create(name='cdh-azml-dev-mlw', subscription_id='320d8d57-c87c-4434-827f-59ee7d86687a', resource_group='csels-cdh-dev'), name=breast-cancer, id=breast-cancer:1, version=1, tags={}, properties={})

NameError: name 'Workspace' is not defined